server:
  port: 9527

spring:
  application:
    name: cloud-getway-service
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: payment_routh
            #uri: http://localhost:8001
            uri: lb://cloud-payment-service
            predicates:
              - Path=/payment/get/**

          - id: payment_routh2
            #uri: http://localhost:8001
            uri: lb://cloud-payment-service
            predicates:
              - Path=/payment/discovery/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #主机名
    instance-id: cloud-getway
    #显示ip地址
    prefer-ip-address: true